version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    hostname: redis
    networks:
        - redis-net
    volumes:
        - redis-data:/data
  
  app:
    build: .
    links:
      - redis
    # environment:
    #   - REDIS_URL=redis://cache
    env_file: 
        - vars.env
    networks:
      - redis-net
    depends_on:
      - redis