version: "3.8"
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379"
    hostname: redis
    networks:
        - redis-net
    volumes:
        - ./db:/data
  
  app:
    build: .
    links:
      - redis
    user: root
    # environment:
    #   - REDIS_URL=redis://cache
    env_file: 
        - ./vars.env
    networks:
      - redis-net
    depends_on:
      - redis


networks: 
  redis-net: